name: Render Video
on:
  workflow_dispatch: # This allows you to start the render manually

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Render Video
        run: npx remotion render src/index.ts out/video.mp4

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: out/video.mp4
